import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import questions_collection

QUESTIONS = [
    {
        "id": "q1",
        "question": "If 3x + 7 = 22, what is the value of x?",
        "options": ["3", "4", "5", "6"],
        "correct_answer": "5",
        "difficulty": 0.2,
        "topic": "Algebra",
        "tags": ["linear-equations", "basic"],
    },
    {
        "id": "q2",
        "question": "What is the slope of the line 2y = 6x + 4?",
        "options": ["2", "3", "4", "6"],
        "correct_answer": "3",
        "difficulty": 0.3,
        "topic": "Algebra",
        "tags": ["slope", "linear-equations"],
    },
    {
        "id": "q3",
        "question": "Solve for x: x² - 9 = 0",
        "options": ["±2", "±3", "±4", "±9"],
        "correct_answer": "±3",
        "difficulty": 0.4,
        "topic": "Algebra",
        "tags": ["quadratic", "factoring"],
    },
    {
        "id": "q4",
        "question": "If f(x) = 2x² + 3x - 5, what is f(2)?",
        "options": ["7", "9", "5", "11"],
        "correct_answer": "9",
        "difficulty": 0.5,
        "topic": "Algebra",
        "tags": ["functions", "evaluation"],
    },
    {
        "id": "q5",
        "question": "What is the sum of the roots of x² - 7x + 12 = 0?",
        "options": ["5", "6", "7", "12"],
        "correct_answer": "7",
        "difficulty": 0.6,
        "topic": "Algebra",
        "tags": ["quadratic", "vieta"],
    },
    {
        "id": "q6",
        "question": "What is the area of a triangle with base 10 and height 6?",
        "options": ["20", "30", "40", "60"],
        "correct_answer": "30",
        "difficulty": 0.2,
        "topic": "Geometry",
        "tags": ["area", "triangle"],
    },
    {
        "id": "q7",
        "question": "What is the circumference of a circle with radius 7? (Use π ≈ 22/7)",
        "options": ["22", "44", "154", "88"],
        "correct_answer": "44",
        "difficulty": 0.3,
        "topic": "Geometry",
        "tags": ["circle", "circumference"],
    },
    {
        "id": "q8",
        "question": "In a right triangle, if one leg is 5 and the hypotenuse is 13, what is the other leg?",
        "options": ["8", "10", "12", "11"],
        "correct_answer": "12",
        "difficulty": 0.5,
        "topic": "Geometry",
        "tags": ["pythagorean", "right-triangle"],
    },
    {
        "id": "q9",
        "question": "What is the volume of a cylinder with radius 3 and height 10? (Use π ≈ 3.14)",
        "options": ["94.2", "282.6", "188.4", "314.0"],
        "correct_answer": "282.6",
        "difficulty": 0.6,
        "topic": "Geometry",
        "tags": ["volume", "cylinder"],
    },
    {
        "id": "q10",
        "question": "Two parallel lines are cut by a transversal. If one alternate interior angle is 65°, what is the other?",
        "options": ["65°", "115°", "25°", "90°"],
        "correct_answer": "65°",
        "difficulty": 0.4,
        "topic": "Geometry",
        "tags": ["angles", "parallel-lines"],
    },
    {
        "id": "q11",
        "question": "Choose the word most similar in meaning to 'Ephemeral':",
        "options": ["Eternal", "Fleeting", "Sturdy", "Ancient"],
        "correct_answer": "Fleeting",
        "difficulty": 0.3,
        "topic": "Vocabulary",
        "tags": ["synonyms", "gre-words"],
    },
    {
        "id": "q12",
        "question": "Choose the word most opposite in meaning to 'Gregarious':",
        "options": ["Sociable", "Reclusive", "Generous", "Garrulous"],
        "correct_answer": "Reclusive",
        "difficulty": 0.4,
        "topic": "Vocabulary",
        "tags": ["antonyms", "gre-words"],
    },
    {
        "id": "q13",
        "question": "Select the best synonym for 'Ubiquitous':",
        "options": ["Rare", "Unique", "Omnipresent", "Ambiguous"],
        "correct_answer": "Omnipresent",
        "difficulty": 0.5,
        "topic": "Vocabulary",
        "tags": ["synonyms", "gre-words"],
    },
    {
        "id": "q14",
        "question": "The word 'Obfuscate' most nearly means:",
        "options": ["Clarify", "Confuse", "Illuminate", "Decorate"],
        "correct_answer": "Confuse",
        "difficulty": 0.7,
        "topic": "Vocabulary",
        "tags": ["definitions", "gre-words"],
    },
    {
        "id": "q15",
        "question": "Choose the word that best completes: 'The politician's ______ speech failed to address any real issues.'",
        "options": ["Cogent", "Vacuous", "Eloquent", "Trenchant"],
        "correct_answer": "Vacuous",
        "difficulty": 0.8,
        "topic": "Vocabulary",
        "tags": ["sentence-completion", "gre-words"],
    },
    {
        "id": "q16",
        "question": "A passage states: 'The discovery rendered previous models obsolete.' What does 'rendered' mean here?",
        "options": ["Drew", "Made", "Returned", "Surrendered"],
        "correct_answer": "Made",
        "difficulty": 0.3,
        "topic": "Reading",
        "tags": ["context-clues", "vocabulary-in-context"],
    },
    {
        "id": "q17",
        "question": "An author writes: 'Despite mounting evidence, the committee remained intransigent.' The author's tone is best described as:",
        "options": ["Supportive", "Critical", "Neutral", "Celebratory"],
        "correct_answer": "Critical",
        "difficulty": 0.5,
        "topic": "Reading",
        "tags": ["tone", "inference"],
    },
    {
        "id": "q18",
        "question": "Which of the following best describes the purpose of a thesis statement in an argumentative essay?",
        "options": [
            "To summarize the conclusion",
            "To present the main argument",
            "To provide background information",
            "To list supporting evidence",
        ],
        "correct_answer": "To present the main argument",
        "difficulty": 0.4,
        "topic": "Reading",
        "tags": ["essay-structure", "comprehension"],
    },
    {
        "id": "q19",
        "question": "If a passage contrasts 'traditional methods' with 'innovative approaches,' the organizational pattern is:",
        "options": [
            "Cause and effect",
            "Compare and contrast",
            "Chronological order",
            "Problem and solution",
        ],
        "correct_answer": "Compare and contrast",
        "difficulty": 0.6,
        "topic": "Reading",
        "tags": ["text-structure", "comprehension"],
    },
    {
        "id": "q20",
        "question": "An author argues that urban green spaces improve mental health, citing three studies. This is an example of:",
        "options": [
            "Anecdotal evidence",
            "Appeal to authority",
            "Empirical support",
            "Logical fallacy",
        ],
        "correct_answer": "Empirical support",
        "difficulty": 0.7,
        "topic": "Reading",
        "tags": ["reasoning", "evidence"],
    },
    {
        "id": "q21",
        "question": "Simplify: (3x²y)(4xy³)",
        "options": ["12x³y⁴", "7x³y⁴", "12x²y³", "7x²y³"],
        "correct_answer": "12x³y⁴",
        "difficulty": 0.5,
        "topic": "Algebra",
        "tags": ["exponents", "polynomials"],
    },
    {
        "id": "q22",
        "question": "What is the interior angle sum of a hexagon?",
        "options": ["540°", "600°", "720°", "900°"],
        "correct_answer": "720°",
        "difficulty": 0.4,
        "topic": "Geometry",
        "tags": ["polygons", "angles"],
    },
    {
        "id": "q23",
        "question": "Choose the word most similar in meaning to 'Pernicious':",
        "options": ["Beneficial", "Harmful", "Transparent", "Cautious"],
        "correct_answer": "Harmful",
        "difficulty": 0.6,
        "topic": "Vocabulary",
        "tags": ["synonyms", "gre-words"],
    },
    {
        "id": "q24",
        "question": "A researcher claims correlation implies causation. This is an example of:",
        "options": [
            "Valid reasoning",
            "A logical fallacy",
            "Inductive reasoning",
            "Empirical evidence",
        ],
        "correct_answer": "A logical fallacy",
        "difficulty": 0.8,
        "topic": "Reading",
        "tags": ["critical-reasoning", "fallacies"],
    },
    {
        "id": "q25",
        "question": "If log₂(x) = 5, what is x?",
        "options": ["10", "25", "32", "64"],
        "correct_answer": "32",
        "difficulty": 0.7,
        "topic": "Algebra",
        "tags": ["logarithms", "exponents"],
    },
]


def seed():
    questions_collection.delete_many({})
    questions_collection.insert_many(QUESTIONS)
    print(f"Seeded {len(QUESTIONS)} questions into the database.")


if __name__ == "__main__":
    seed()
